/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrador' at '7/02/17 10:16' with Gradle 2.14.1
 *
 * @author Administrador, @date 7/02/17 10:16
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
